require:
  - rubocop-performance

AllCops:
  Include:
    - bin/*
    - lib/**/*.rb
  TargetRubyVersion: 2.5
  NewCops: enable


Layout/LineLength:
  Max: 110 # Preferred length is 100
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 8
  MaxOptionalParameters: 8

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 5


Style/Encoding:
  Enabled: false

Style/StringLiterals:
  Enabled: false # we don't care

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/NumericLiterals:
  MinDigits: 6

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  MinSize: 5

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: lambda

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TernaryParentheses:
  EnforcedStyle: require_no_parentheses

Style/FormatString:
  EnforcedStyle: sprintf

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/EmptyElse:
  EnforcedStyle: empty

Style/CaseEquality:
  Enabled: false

Style/GuardClause:
  Enabled: false # false alarms

Lint/MissingSuper:
  Enabled: false # why the need to fallback to super?

Style/Next:
  Enabled: false # not really useful

Style/ParallelAssignment:
  Enabled: false # not really needed

Style/TrivialAccessors:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false # compact nested ternary operators are okay

Style/RescueModifier:
  Enabled: false # valid but using it makes life sometimes easier

Style/MutableConstant:
  Enabled: false # valid but sometimes unavoidable

Style/CommentedKeyword:
  Enabled: false # false alarms and we do want yield comments on that line

Style/StderrPuts:
  Enabled: false # false alarms because not all $stderr.puts messages are Ruby style warnings

Style/PerlBackrefs:
  Enabled: false # sometimes there are no good alternatives

Style/IfUnlessModifier:
  Enabled: false # useful but sometimes the meaning is better conveyed using an if/unless statement

Style/InfiniteLoop:
  Enabled: false # why should Kernel#loop be better than while true?

Style/SpecialGlobalVars:
  Enabled: false # I think that $! and $? are recognizable in terms of their function

Style/MultipleComparison:
  Enabled: false # why should an array be created? especially if only two items are compared

Style/AccessModifierDeclarations:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false # I prefer to use either one or the other, depending on context

Style/FormatStringToken:
  Enabled: false # I don't care about this

Style/ClassAndModuleChildren:
  Enabled: false


Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit
  Exclude:
    - lib/kramdown/converter/latex.rb # false positive

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false # we have the magic comment and then the license

Layout/AssignmentIndentation:
  Enabled: false # false alarms


Naming/HeredocDelimiterNaming:
  Enabled: false # we like our delimiters short and obvious

Naming/MethodParameterName:
  Enabled: false # for points the names x,y are perfectly reasonable

Lint/LiteralAsCondition:
  Enabled: false # we use while true

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Performance/FixedSize:
  Enabled: false


Security/Open:
  Enabled: false



Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Style/EnvHome:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/CaseLikeIf:
  Exclude:
    - lib/kramdown/options.rb # false positive
Performance/CollectionLiteralInLoop:
  Enabled: false # for now, enable later and fix
Style/HashLikeCase:
  Exclude:
    - lib/kramdown/converter/kramdown.rb
Style/MissingRespondToMissing:
  Enabled: false
